### ISSUE TITLE
Question re excluding errors from responses - does this approach seem reasonable?

### ISSUE THREAD

**Issue by maxnachlinger** [restify/node-restify#1013]
I want to make sure that error details are never sent out as responses, and the best way to achieve that seemed to be via the formatters. I've probably missed some more obvious way to achieve this, but here's what I came up with.  Does this seem reasonable (or is there a simpler solution)? 
```javascript
const server = restify.createServer()

// wraps all formatters in a function filtering out Error bodies
Object.keys(server.formatters).forEach((name) => {
  const formatter = server.formatters[ name ]

  server.formatters[ name ] = (req, res, body, next) => {
    // keep possibly sensitive details from going out in error messages
    if (body instanceof Error &&
      !(body instanceof errors.HttpError) &&
      !(body instanceof errors.RestError)
    ) {
      body = new errors.InternalServerError('Internal Server Error')
    }

    return formatter(req, res, body, next)
  }
})
```

**Comment by maxnachlinger** [comment]
Egad! This is most likely a misuse of Github issues - sorry about that. I've opened a question on StackOverflow for great good :)

**Comment by DonutEspresso** [comment]
No problem! The approach you've taken definitely works. I might suggest that rather than creating a new error, to wrap the existing error using something like [verror](https://github.com/davepacheco/node-verror) or [restify-errors](https://github.com/restify/errors) to wrap the existing error. 

That way your audit logs or anything else will maintain the full error stack, while only the top level Internal Server Error is sent out to the client.
