### ISSUE TITLE
Remove next(err)

### ISSUE THREAD

**Issue by lukealbao** [restify/node-restify#1019]
``` javascript
server.get('/oops', 
           function clientFacing (req, res, next) {
             if (successful) res.send(202);
             return next();
           },
           function taskHandler (req, res, next) {
             var err = new InternalServerError('Some other service failed');
             return next(err);
           });
```

If you want to use the `next(err)` pattern, you currently have to ensure that no previous handlers have called `res.send`. Otherwise, you will get an uncaught exception for attempting to set headers after they've been sent. This hides the actual exception you are meaning to catch.

**Comment by lukealbao** [comment]
Sorry about the multiple references. I got confused with the other users' commits being part of the PR. The only relevant commit is 289b2f8eb3f3c22472f71f30b1c702da6a71d0c0. Thanks!

**Comment by DonutEspresso** [comment]
Thanks for the report. It does seem `next(err)`'s sugar for automatically calling `res.send` can be a little confusing. I've run into it myself recently. I think there's a good argument for being consistent with the sugar, i.e., either always using `next()` for `res.send` or never do it all. Otherwise, the behavior can become really unclear.

As in your example, you do want the error propagated through the system, just not sent to the client. I'd almost rather remove the `next([param])` pattern because it mixes a few different concerns, not least of which is also the `next(false)` which is an entirely different use case.

**Comment by lukealbao** [comment]
Thanks, Alex. I'm not sure I understand when you mention being consistent with the sugar. Do you mean that the user should choose, or the behavior of `next` should be changed?

**Comment by DonutEspresso** [comment]
Sorry, what I mean is that `next()` does many things, i.e.,

- `next(err)` =  "call res.send(err), fire an error event, stop executing handler chain"
- `next(false)` = "response has already been sent, stop executing handler chain"
- `next()` =  "move on to next handler" 

In your original example, based on the current contract of `next()`, I would say your code has a bug (calling res.send() twice, since that's what the `next(err)` sugar does for you).

But I suspect what you're after is the "fire an error event" part of `next(err)`, but not the `res.send()` part of it. Does that sound right?

**Comment by lukealbao** [comment]
Gotcha, thanks. That is what I thought you meant. And you're right, that's how I want `next` to behave in this case. 

I wasn't sure if the PR request I submitted (now #1026 with a single commit) was considered sketchy because it could result in some confusion in the case where a user relies on `next(err)` to send a response, but the response does not contain the `RestError` the user expects. To my mind, said user would quickly be able to deduce where `res.send` is being called, so it's not terribly confusing. 

An alternative, like you say, would be to remove `res.send` altogether from the `next(err)` case. I think that's a viable choice, as most folks doing this are going to be adding an error listener or several, and can call `res.send` there. But I looked into that, and it breaks a number of tests. Seems more drastic a change. My proposed fix simply doesn't call `res.send` if the response is already finished. 

Any thoughts on if that would work?

**Comment by DonutEspresso** [comment]
I think implications here are around breaking the contract when it comes to handling errors from the server point of view. Today, the contract is `next(err)` => error event/listener => send the response => stop processing. That is, the error handling mechanisms are intimately tied to the server emitted events as well as the response.

If you want to leverage the server error events to do things "out of band" but also _continue_ processing, that breaks the above contract. I see the value in this, but not entirely sure we want to break the existing contract at the same time. While you _could_ do this in userland, it means you have to wire up your own error instanceof determination to do the right thing, which seems silly if restify is doing this for you already. 

@yunong, we talked about this the other day, thoughts?

**Comment by lukealbao** [comment]
I don't think this is an attempt to overload server events with out of band work. In the above example, the `clientFacing` handler could and would use the `next(err)` pattern and everything would work as expected.

The problem is that calling `next(err)` causes a call to `res.send` without regard to the actual state of the response. If the response has been sent by an upstream handler (as it does in the example), it will still attempt to send it which to me says that the contract itself is wrong. I am hoping for a way to make it something more like this:

`next(err)` => emit event => send response *only if possible* => stop chain.

**Comment by DonutEspresso** [comment]
Yeah, I'm totally on board, I think what I was trying to say re: the contract is that currently the server error events are intimately tied to the response, so decoupling those will have other implications. That's what I meant by "out of band", because you want to use the server events for things not related to the response itself. To me the options seem to be:

1) keep the current `next(err)` behavior, but give you new mechanisms to leverage the error events independent of the response (doesn't entirely address the current problem of res.send() getting called twice, and muddies the semantics, so I dont like this approach)
2) decouple `res.send()` sugar from `next(err)` entirely, perhaps with an opt-in flag

I'd like some of the other folks to chime in though. @yunong, @micahr ?

**Comment by micahr** [comment]
I'm in favor of 2⃣️. We should move towards removing the logic from the opaque `next` call. Perhaps we can introduce the option flag in 5.x and potentially make it default in 6.x?
