### ISSUE TITLE
Best way to instantiate Restify request and response object?

### ISSUE THREAD

**Issue by serv** [restify/node-restify#1180]
Many of our functions use response and request objects as arguments.
In order to create unit tests for these functions, I am researching what the best way might be to try to create restify response and request objects.
Restify request and response modules are not exported.
What is the best way to get a response and request object that could be used for unit testing a function that takes response and request objects are arguments?

**Comment by micahr** [comment]
Because those objects are internal to the implementation of Restify we don't want to export them if we can avoid it. A better approach would be to create a test mock within your project to mimic the behavior you are looking for. The request and response objects are mostly POJOs that have a few methods added to them and it wouldn't be too tough to write mocks for the parts you rely on.

**Comment by DonutEspresso** [comment]
Yep, I'll second that. Mocking is a fairly low cost way to do it for unit testing, since in most cases you are likely relying on specific items you have stored on the req object, or things like req.query or req.params which are easily mockable. You could also "record" a request and store the state that you care about as a mock req object.  

Anything more complex than that starts to get you into the land of integration tests, where you'll likely want to spin up a server and simply run the request through the real thing.

**Comment by serv** [comment]
Thanks. Since req and res are just POJOs, I should be able to mock it easily even if I cannot use the exact req and res objects.
