### ISSUE TITLE
restify.createJsonClient is not a function

### ISSUE THREAD

**Issue by SeaOfTea** [restify/node-restify#1188]
```
var restify = require('restify');

// Creates a JSON client
var client = restify.createJsonClient({
  url: 'https://us-east-1.api.joyent.com'
});


client.basicAuth('$login', '$password');
client.get('/my/machines', function(err, req, res, obj) {
  assert.ifError(err);

  console.log(JSON.stringify(obj, null, 2));
});
```

This code now no longer works on the latest version of restify. v5. The docs still indicate that this is the way of creating and using a client.

**Comment by SeaOfTea** [comment]
Reading more about it and I understand you have moved the clients into their own npm module. However the docs there still use the code snippet above.
https://www.npmjs.com/package/restify-clients

**Comment by SeaOfTea** [comment]
For anyone that comes across this issue, the code instead is now:

`npm install --save restify-plugins`
```
var restify = require('restify-plugins');

// Creates a JSON client
var client = restify.createJsonClient({
  url: 'https://us-east-1.api.joyent.com'
});


client.basicAuth('$login', '$password');
client.get('/my/machines', function(err, req, res, obj) {
  assert.ifError(err);

  console.log(JSON.stringify(obj, null, 2));
});
```
No explanation as to any of this on http://restify.com/#client-api

**Comment by micahr** [comment]
Apologies, we accidentally published the 5.0.0 beta under the latest tag in NPM, which meant everyone who ran: `npm install restify` got it by default. This is certainly not the expected behavior and we have since reverted the `latest` tag to address this issue. 

Prior to publishing Restify 5 we will be releasing our 4.x to 5.x migration guide which will highlight the various changes (including the one you discovered).

We do apologize for the inconvenience and confusion.

**Comment by SeaOfTea** [comment]
@micahr Thanks for your quick response. I must have ran `npm install` at just the wrong moment.
I'll be happy to close this then unless you wanted to keep it open for any reason.

**Comment by micahr** [comment]
No problem. We left it in a bad state for a couple of days, so it is totally our fault.
