### ISSUE TITLE
`res.cache()` returning [] instead of this?

### ISSUE THREAD

**Issue by jylinman** [restify/node-restify#1207]
https://github.com/restify/node-restify/blob/c64c78a55d2693a6b7b1ffe0159a9b934cf3e84a/lib/response.js#L58

I am a little confused as to why this is returning an array of headers instead of returning `this`.  From the documentation and some samples I have seen online the use case is `res.cache({ maxAge: 300 }).send();` but that would fail (as it just failed in my code) because of the return.  Is there something I am missing or could we return `this` like the function below it?

**Comment by DonutEspresso** [comment]
Since `res.cache` is just setting a header, the return value is the same as calling `res.header()` (the value set for the header). I think this behavior is expected and consistent within restify. 

I don't have the historical context for this choice, however, and it certainly seems like we could return the response object to allow for further chaining. This would definitely be a breaking change, however.

**Comment by jylinman** [comment]
Yeah no problem.  It would be a breaking change and there really isn't a need for that.  Thanks!

**Comment by jylinman** [comment]
Yeah no problem.  It would be a breaking change and there really isn't a need for that.  Thanks!
