### ISSUE TITLE
Migrating to beta - CORS middleware

### ISSUE THREAD

**Issue by royibernthal** [restify/node-restify#1266]
I recently migrated to restify beta, and following that restify.CORS is no longer available.
I tried to use the restify-cors-middleware module but it doesn't work, when I looked closely at the npm list of installed modules I noticed it's not even supposed to work for restify beta? (beta is version 5 and above)

> npm ERR! peer dep missing: restify@2.6.x - 4.3.x, required by restify-cors-middleware@0.0.8

If that is the case, is there another way for me to use CORS in the beta?

**Comment by royibernthal** [comment]
Is there no solution for it at all in the beta?

**Comment by yunong** [comment]
The CORS plugin has been deprecated in 5.x, we've been steering people to: https://github.com/TabDigital/restify-cors-middleware instead.

**Comment by royibernthal** [comment]
This is what I'm using, it's not working for me.

**Comment by rprieto** [comment]
Hi @yunong, one of the maintainers of https://github.com/TabDigital/restify-cors-middleware here. We're very happy that you like our implementation of CORS! Here's 2 things we'd need to look at to make it work on Restify 5, and make the integration more stable:

### 1.  Preflight requests

The part that breaks in Restify 5 is the following line:

```js
var DEFAULT_ALLOW_HEADERS = restify.CORS.ALLOW_HEADERS;
```

I'll have a look at other ways we can get the default list of headers allowed by Restify. We could bake it into the plugin (copy-pasted from [lib/plugins/cors.js#L10](https://github.com/restify/node-restify/blob/master/lib/plugins/cors.js#L10)), however hard-coding headers like `x-api-version` doesn't seem very future-proof. Can you think of a stable way to get it dynamically?

### 2. Actual requests

Because the main problems with CORS were in **preflight** requests, we only implemented preflight.... and simply delegate **actual** requests back to Restify :smile: Of course this would have to change if you delete [lib/plugins/cors.js](https://github.com/restify/node-restify/blob/master/lib/plugins/cors.js).

I'm happy to simply import the code as-is into our plugin. We'll just have the same questions as above: how can we get the list of exposed headers in a stable way, e.g. `api-version`?

Thanks!

**Comment by royibernthal** [comment]
Hey @yunong @rprieto, any update on that?

**Comment by DonutEspresso** [comment]
Whoops, looks like some crossed wires here! I think we assumed incorrectly that restify-cors-middleware replaces CORS wholesale within restify. If that's not the case, I think our effort is better focused by getting the work started [over here](https://github.com/restify/plugins/pull/10) compliant with the existing tests @rprieto and folks have put together for the restify-cors-middleware plugin. 

That said, @royibernthal it's unlikely any of the maintainers will have a chance to get to that work anytime soon. :(   I'd recommend falling back on 4.x if CORS is something blocking your progress - given it's beta status there are still a few kinks to work out and we wouldn't recommend using it in production just yet.

**Comment by rprieto** [comment]
No problem. It's actually trivial for us to pull in the "actual" request support, hence breaking the cycle. Happy to start working on that tomorrow, and we can aim to release a new version soon.

**Comment by rprieto** [comment]
If @roblav96, what do you mean? This is about creating a new CORS plugin, instead of relying on `fullResponse` which I think only supports `Access-Control-Allow-Origin: *`.

**Comment by roblav96** [comment]
@rprieto Oh, I didn't fully read everything.

Add custom headers in the `opts` route
```typescript
server.opts(/.*/, function(req, res, next) {
	res.header('Access-Control-Allow-Origin', '*')
	res.header('Access-Control-Allow-Methods', req.header('Access-Control-Request-Method'))
	res.header('Access-Control-Allow-Headers', req.header('Access-Control-Request-Headers'))
	res.send(200)
	return next()
})
```

**Comment by eddieajau** [comment]
Gentle bump. Restify 5 is out, the migration docs notes to use TabDigital's plugin but it is still not compatible with 5 (`TypeError: Cannot read property 'ALLOW_HEADERS' of undefined`).

What do you want to do?

**Comment by rprieto** [comment]
Hi, I just pushed `restify-cors-middleware@1.0.0`, can you let me know if it works?

**Comment by eddieajau** [comment]
Looking better now. No error. But, can you take the peer dependency out of `package.json`?

```sh
npm WARN restify-cors-middleware@1.0.0 requires a peer of restify@2.6.x - 4.3.x but none was installed.
```

**Comment by eddieajau** [comment]
And thanks for the quick response. Sorry :)

**Comment by jqsjqs** [comment]
+1 for updating the peer dependency. Preventing me from deploying various updates to Heroku.

**Comment by rprieto** [comment]
Can you try version `1.0.1`? The peer dependency should now have `restify: 2.6-5`.

**Comment by EvgenyOrekhov** [comment]
@rprieto `restify-cors-middleware@1.0.1` works fine with `restify@5.2.0`.

**Comment by retrohacker** [comment]
Closing as this appears to be fixed in restify-cors-middleware

**Comment by edgracilla** [comment]
does this hurt? 
`npm WARN restify-cors-middleware@1.0.1 requires a peer of restify@2.6.x - 5.x.x but none was installed.`

im using `restify@6.3.2`

**Comment by retrohacker** [comment]
@edgracilla the latest version of restify-cors-middleware should have solved this.

**Comment by retrohacker** [comment]
Huh, doesn't look like it was published...

**Comment by retrohacker** [comment]
@rprieto any update?

**Comment by retrohacker** [comment]
In the meantime you can use `npm install --save Tabcorp/restify-cors-middleware`

**Comment by edgracilla** [comment]
Warnings gone. Thanks!

**Comment by tapankumar** [comment]
please release new version to NPM.

**Comment by hekike** [comment]
@tapankumar `restify-cors-middleware` is not part of the `restify` organization. You should open an issue here: https://github.com/Tabcorp/restify-cors-middleware
