### ISSUE TITLE
Special chars causing MD5 signature to not match which causes Restify client to throw a Bad Digest Error 

### ISSUE THREAD

**Issue by adamrogas** [restify/node-restify#1301]
Special chars causing MD5 signature to not match which causes Restify client to throw a Bad Digest Error 

specifically when the body contains the ’  it appears the MD5 signature header does not validate which causes the Restify client on the other side to error with Bad Digest 

Char	Dec	Hex	Oct
’	146	92	222

**Comment by adamrogas** [comment]
investigating this further it appears to be a mis-match using restify 4.3 and 4.2 together when special chars are present

**Comment by DonutEspresso** [comment]
Thanks for the report - any chance you have a code sample or snippet we cause to reproduce the issue?

**Comment by retrohacker** [comment]
Hey @adamrogas, it looks like a repro case was requested back in April. I'm going to close this issue as stale for now due to inactivity. If the problem persists and you still need help, please read our shiny new [ISSUE_TEMPLATE.md](https://raw.githubusercontent.com/restify/node-restify/5.x/.github/ISSUE_TEMPLATE.md) :heart: we would be happy to help work on this with you
