### ISSUE TITLE
uncaughtException to close connection

### ISSUE THREAD

**Issue by chemdrew** [restify/node-restify#1308]
Just want to bring the idea of closing the tcp connection on an uncaught exception.

If an uncaught exception occurs, that current tcp connection is killed and could cause clients to hang when trying to connect in subsequent requests.

This might make the library too opinionated though since it's adding it's own http standards - happy to discuss and make a PR.

Current way to keep subsequent client connections from hanging when an uncaughtException is thrown:
```
server.on('uncaughtException', (req, res, route, err) => {
  res.setHeader('Connection', 'close');
  res.send(err);
});
```

**Comment by retrohacker** [comment]
Hey @chemdrew,

This pattern sounds super useful, though I agree with you about it being opinionated. It also changes the default behavior of the restify server in a non-trivial way. If not in the core library, this pattern probably belongs some place between a module and a "best practices" guide in the documentation.

Perhaps it would help if you could put together an example case where handling an `uncaughtException` would keep subsequent connections from hanging?

**Comment by chemdrew** [comment]
Hi @retrohacker,

Here is an example, tested in chrome and safari where the first request goes through and the second one will time out without the commented out block

```var restify = require('restify');

const server = restify.createServer({
  name: 'myapp',
  version: '1.0.0'
});

// uncomment the following code to signal the consumer to establish a new connection
// stopping a subsequent request from timing out
/* server.on('uncaughtException', (req, res, route, err) => {
  if (!res.headersSent) res.setHeader('Connection', 'close');
  res.send(err);
}); */

server.get('/test', function (req, res, next) {
  JSON.parse('invalid json - uncaught error');
  return next();
});

server.listen(8080, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```

**Comment by retrohacker** [comment]
Ah I see, I was doing something similar but using `curl` test, and restify closes that connection at the end. In chrome et. al. I'm seeing every other connection hang, looking at wireshark it seems the browser tries a new TCP connection after the first one hangs (and it stops sending keep_alive packets).

Looks like the problem is that the TCP connection is inside of a [`domain`](https://github.com/restify/node-restify/blob/5.x/lib/server.js#L1085-L1097), and that domain becomes unusable once the exception gets thrown.

https://nodejs.org/dist/latest-v7.x/docs/api/domain.html#domain_warning_don_t_ignore_errors

While that code snippet does avoid a connection hanging, keeping a server chugging along after an uncaught exception was thrown can be dangerous. The exception was thrown in the context of a domain so it didn't crash the service, but any shared global state for your application could be in a potentially unstable state. This can lead to exploits, memory leaks, or degraded service. It may be better to start shutting down the server and let the load balancer/process manager handle rerouting traffic and restarting the process.

After looking into this, automatically sending `Connection: close` seems reasonable here since we don't want the client to re-use the TCP connection. Ideally future requests from that client will get routed to another server as the original shuts down.  Leaving the TCP connection open to a borked domain can lead to some really strange and hard to triage bugs. I'm :+1: on closing the connection being the default behaviour in v5, if other maintainers agree.

That being said, we may want to consider adding a documentation item around best practices that shows how to gracefully shutdown a server on an uncaught exception, and explains why that would be desirable.

**Comment by chemdrew** [comment]
Thanks for the detailed explanation. I'm 👍 for closing this too.

That makes a lot more sense to shut down the process since the client/consumer shouldn't have to worry about connection state, that should get handled where the traffic gets routed.
changing my code now!

**Comment by yunong** [comment]
Domains support will be deprecated in 5.x. Closing this issue for now. With that said if you want this behaviour, you can always add it to your codebase via a userland module.
