### ISSUE TITLE
Convert JSCS to eslint

### ISSUE THREAD

**Issue by retrohacker** [restify/node-restify#1315]
JSCS [merged with eslint](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.x0o1xqkk9) a little while ago. It may make sense to migrate our JSCS config over to eslint since we are using both projects.

https://www.npmjs.com/package/polyjuice/ can automate this for us

**Comment by yunong** [comment]
@retrohacker Thanks for the tip. Since the projects are merging, it definitely makes sense to migrate. However, I would propose that we explicitly separate the style configs from the lint configs. It makes it cleaner and more obvious.

My recommendation would be that we keep both of our `make` tasks of `style` and  `lint`, and either have two `.eslintrc` files, or separate sections in the `.eslintrc` file for style and lint.

**Comment by retrohacker** [comment]
Sounds good to me!

**Comment by hekike** [comment]
@retrohacker @yunong do you still want to keep both `jscs` and `eslint`?

Currently, I'm facing the following issue with JSCS: https://github.com/jscs-dev/node-jscs/issues/1939 while I'm working on JSDoc.

I'm wondering if it's still necessary to have both in the project. ESLint handles spaces in JSDoc perfectly.

Also `jscs` is not maintained anymore and is merged with `eslint` see https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.x0o1xqkk9

**Comment by hekike** [comment]
Closed by: https://github.com/restify/node-restify/pull/1527
