### ISSUE TITLE
Migrate restify/plugins back into the restify repo

### ISSUE THREAD

**Issue by yunong** [restify/node-restify#1317]
The restify plugins used to live in the restify repo, but we had moved them out some time ago in the spirit of decoupling the code.

However, there were some unintended consequences of this. Namely, versioning the plugins against multiple versions of restify is impossible.

Since plugins and restify are SemVer'd differently, there's currently no way to track a version of a plugin against a specific version of restify. As the interface of restify changes with each major version, so too must plugins, but then there's no way to keep plugins compatible with older versions of restify.

I've gotten alignment with @DonutEspresso and @micahr and we'll be moving restify-plugins back into this repo.

cc @retrohacker

**Comment by stevehipwell** [comment]
Is this the best solution or could more be done to align the semver for both projects and utilise a peer dependency range for *restify* in *restify-plugins*?

**Comment by retrohacker** [comment]
Hey @stevehipwell,

Thanks for engaging this. I'll be tackling this in the next few days (I'm focusing on cleaning up the GitHub issues and PRs first).

I'm inclined to agree with you. Personally, I'd like to see each plugin broken out into it's own module. The rational is that forcing restify to have a _clear_ and _concise_ API for each "type" of plugin would allow for a proper userland to develop where plugins can easily be maintained by non-core contributors outside of the restify repo. Since most plugins boil down to (from my understanding) a `res`/`req` transformation through the middleware stack, this would help us firm up both the API and the plugin "boundaries".

Tightly coupling plugins and the code base blurs the line between "features" and "plugins"

We are already planning on doing this do the `serveStatic` plugin, since serving static content isn't really in the restify wheelhouse. It could be argued that CORS, et. al. are similar in that they aren't actually part of the core "REST" framework, but are additional features for supporting different clients in different environments.

After talking this through and putting together a plan, I'd be happy to do a lot of the work here, but could use some help :heart:

**Comment by stevehipwell** [comment]
@retrohacker I'm happy to help where I can.
