### ISSUE TITLE
[Question] How to audit log redirects?

### ISSUE THREAD

**Issue by eddieajau** [restify/node-restify#1336]
I'm using Restify with Passort and am adding a login route something like this:

```js
server.get('/login', this.passport.authenticate('azuread-openidconnect', { /* options */ });

server.on('after', auditLogger({ log: logger }));
```

However, it appears that `authenticate` never calls the `next` that is passed to it so the `after` event is never emitted.

Do you have any suggestions for audit logging this type of request?

Thanks in advance.

**Comment by DonutEspresso** [comment]
The `after` event fires when a request is considered complete. The requirements for completion are:

* handler chain is `next`ed to the end
* `next` is called with an error at some point in the chain

[It looks like](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L251) `next` is getting called on a successful login, and in error cases `next` is also called with an error. I am not familiar with Passport, but a cursory glance looks like it is doing the right thing. I'd recommend asking over at the Passport repo to ensure they are always calling next when it has completed its work. 

One key difference between restify and express is that restify doesn't automatically consider a request complete after flushing a response, since it is possible to do additional work after flushing a response. This is a general caveat to keep in mind when using plugins designed for express. 

I don't know if documented, but looks like you can also [call passport.authenticate manually](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L44). That may give you more control over the nexting behavior.

Good luck, and let us know what you find! I am sure it would be very helpful for other users who have run into the same thing.
