### ISSUE TITLE
How to correctly error in `multipartFileHandler`

### ISSUE THREAD

**Issue by eddieajau** [restify/node-restify#1404]
How does/could one correctly error in the `multipartFileHandler ` option? For example, a simple extension filter could like like this:

```javascript
const path =  require('path');
const validExtensions = ['.png', '.jpg', '.jpeg', '.gif'];

function notValid(filename) {
  return validExtensions.indexOf(path.extname(filename).toLowerCase()) === -1;
}

server.use(restify.plugins.bodyParser({
    multipartFileHandler: (part) => {
        if (notValid(part.filename)) {
            // >>> WHAT TO DO HERE ??? <<<
        }

        part.on('data', function(data) {
          /* do something with the multipart file data */
        });
    }
 }));
```

If I had access to the `form` object, I could do something like:

```javascript
form._error(new Error('extention not supported'));
```

but that object is not directly available.

Thoughts? Suggestions? Thanks in advance.

**Comment by retrohacker** [comment]
Sorry that you didn't get a response @eddieajau...

I don't have the context here to answer your questions :disappointed: 

Since this was from July, I'm going to close it as stale. If it is still giving you problems, could you ping us on this issue and I'll gladly re-open it.

P.S. if by chance you did get this figured out, would you mind commenting with your solution for future people who find their way here from search engines?
