### ISSUE TITLE
Closing server tremendously slow after an uncaughtException

### ISSUE THREAD

**Issue by simonepri** [restify/node-restify#1426]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report
server.close is tremendously slow if called after an `uncaughtException`
## Restify Version
5.0.1
## Node.js Version
8.1.4
## OS
macOS 10.12.6

## Expected behaviour
The server should close faster.
Restify shouldn't allow incoming requests if close is called.

## Actual behaviour
Takes ages to close the server.
![image](https://user-images.githubusercontent.com/3505087/28830968-a287c9ba-76d8-11e7-9091-31f0b35b885f.png)
Furthermore requests continues to be processed while waiting the server closure.
![image](https://user-images.githubusercontent.com/3505087/28831311-84b899ae-76d9-11e7-9477-1d7970e39e14.png)

## Repro case
```

const restify = require('restify');
let start;

server = restify.createServer();

server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());

server.get('/test', (req, res, next) => {
  start = Date.now();
  res.json({status: 'ok', success: true});
  console.log(x); // This will cause an uncaughtException
  return next();
});

server.listen(2300, () => {
  console.log('%s listening at %s', server.name, server.url);
});

process.on('uncaughtException', () => {
  console.log('uncaughtException');

  server.close(() => {
    console.log('Closed after ', (Date.now()-start), 'ms');
    process.exit(1);
  });
});
```
Simply get at localhost:2300/test

## Cause

Probably this is not related to Restify but to nodejs itself.
Or maybe is just an OS related problem.

We should add something that stops Restify to pass requests to user defined routes if .close is called.

## Are you willing and able to fix this?
"Yes" if related to Restify.

**Comment by DonutEspresso** [comment]
Hm, I have your same setup as listed here and am unable to repro with either node6 or node8:

```sh
restify listening at http://[::]:2300
uncaughtException
Closed after  4 ms
```

@simonepri Do you see the same with node6?

**Comment by simonepri** [comment]
@DonutEspresso same behavior on node6 :(
![image](https://user-images.githubusercontent.com/3505087/29007421-4c901862-7b03-11e7-9322-6d321bde08f2.png)

What I've seen is that if the error happen outside a route the server closes instantantanely.

**Comment by simonepri** [comment]
The problem happen only if the exception happen in a route.

For example with this: 

```
const restify = require('restify');
let start;

server = restify.createServer();

setTimeout(() => {
  start = Date.now();
  console.log(x); // This will cause an uncaughtException
}, 5000);

server.listen(2300, () => {
  console.log('%s listening at %s', server.name, server.url);
});

process.on('uncaughtException', () => {
  console.log('uncaughtException');

  server.close(() => {
    console.log('Closed after ', (Date.now()-start), 'ms');
    process.exit(1);
  });
});
```

It ends in a reasonable time.

![image](https://user-images.githubusercontent.com/3505087/29007485-8a8edf4e-7b04-11e7-89c2-1479badb3c59.png)

**Comment by simonepri** [comment]
What a strange behavior!
The problem it seems to be the Client!

During my tests I was hitting the route directly from the Browser (Chrome).
If I use curl the server closes in time.

![image](https://user-images.githubusercontent.com/3505087/29007555-daa4b9e4-7b05-11e7-8775-0b37b24f334a.png)
![image](https://user-images.githubusercontent.com/3505087/29007550-cdb024e4-7b05-11e7-91f0-07eb77a37c77.png)

How could be that possible?

**Comment by DonutEspresso** [comment]
The browser is setting keep-alive headers in the request. `server.close()` does not forcefully terminate existing connections by design (restify is using node core's server.close method, see: https://github.com/nodejs/node/issues/2642). 

It's unfortunate, but this behavior is by design. There are few work arounds in the referenced thread worth looking at - I woudn't mind rolling this as a possible restify plugin in the future. Certainly feels like a problem everybody is solving on their own in userland!

**Comment by simonepri** [comment]
I will look the thread tomorrow. Thanks again.
The plugin it seems a good idea!

OT:
What do you think about adding the `Client Used` as a default section to fill while open an Issue?
It seems to be really important 😄

**Comment by retrohacker** [comment]
Hey @simonepri,

It may be worth shutting down the process instead of gracefully closing the server and connections. By logging the error and crashing, you will preserve the state of the process for post-mortem debugging. The downside of this is that active connections will timeout before reconnecting but you are already seeing that with `server.close`. Alternatively, you can track the active connections to the server and close them all in your error handler.

We talked a lot about the value of aborting on error in the PR here: https://github.com/restify/node-restify/pull/1319#issuecomment-297846354

I.E. `process.exit()`

**Comment by simonepri** [comment]
I can confirm that the 'Let it crash' principle can be considered a 'best practice'.

But we cannot says that will always fits real world scenarios.
Let's assume your server process payments and something bad happen with a transaction.

This is a quite tricky situation.
We have 2 main possibilities:
* Kill everything immediatly
> This preserves the state of the server but will make users unhappy because their transaction will not be processed!
> Also a server to be killed should be designed to be "Kill Safe" in order to just `let it crash`

* Continue to process all pending requests:
> This can make users happy, because most of the time the exception will not cause troubles, but how knows? 🙈 .
> Continue with a request after an exception may expose the server to unexpected behaviors or even to security flaws.

Another approch could be:
1) stop the processing of the responsible route immediatly
2) close any active connection
3) Wait until any pending route reaches the end of his chain.
5) Kill the process
This will expose us to a minimum risk while allowing us to be less sensible to data loss.
This I think was quite easy to implement using domains, but now are deprecated.

Thank you for the link to the PR interesting read.

**Comment by simonepri** [comment]
With that said I believe that Graceful Shutdown is only appropriate when you want restart or kill the server manually.

**Comment by retrohacker** [comment]
> This preserves the state of the server but will make users unhappy because their transaction will not be processed!

Be careful with this. It may be a good idea to have requests that process payments be idempotent so it is always safe to automatically retry on failure (either the client or load balancer can kick off the retry). Letting the process run in an unstable state when processing payments could be pretty dangerous. At best, someone may get something they didn't pay for. At worse...

Anyways, it looks like this issue has been resolved. The issue is actually the behaviour of Node.js if I'm not mistaken and calling `.close` outside of normal operation probably isn't safe to begin with.

**Comment by retrohacker** [comment]
BTW, thank you for engaging so much on this repo :heart: I was starting to feel lonely here! :smile:

**Comment by simonepri** [comment]
Obviously it was just an example.

Why we don't document such information? I mean we could provide a motivated `best practice` for shutting down the server on exit/restart/unhandled rejections/uncaught exceptions and what are the things to consider in those situations.
