### ISSUE TITLE
request.body undefined causes server crash

### ISSUE THREAD

**Issue by magnusdr** [restify/node-restify#1432]
# Bug Report

## Restify Version 
5.0.1

## Node.js Version
7.10.1

## Expected behaviour

req.body should always be defined.
`if(req.body.email == null)` should not be any issue

## Actual behaviour

Application crashes and returns this error message:

TypeError: Cannot read property 'email' of undefined

Since body is undefined when no data is sent, the nodejs application crashes. This makes the server vulnerable for denial of service attacks.

## Repro case

**repro.js**
```
var restify = require('restify');
var server = restify.createServer();
server.use(restify.plugins.bodyParser());
server.post('/',
  function myFirstRoute(req, res, next){
     if(req.body.email == null)
       res.send("Please specify email");
     else
       res.send("Thanks for email");
  }
);
server.listen(8080);
```

## Cause

In the bodyParser plugin, there is never defined any body if content-type is not application/json.

```
if (req.getContentType() !== 'application/json' || !req.body) {
  next();
  return;
}
```

## Are you willing and able to fix this?

Yes, i have. You can add a custom middleware that creates an empty object for req.body. It makes my index file longer, and i find it unnecessary to include this in order to keep my server stable.

```
server.use(function(req, res, next){
  req.body = {};
  next();
});
```

if just `req.body = {};` is included in the bodyParser plugin, restify will be more stable and not crash.

**Comment by sean3z** [comment]
Thanks for submitting @magnusdr! 

I'd agree that in a lot of cases, `req.body` defaulting to an empty object would be intuitive. However, there are just as many cases where `req.body` [could be a string](https://github.com/restify/node-restify/blob/5.x/lib/plugins/bodyReader.js#L47) or other data types, like an array instead (depending on the body, of course), as it supports multiple Content-Types.

I'm not sure how the restify owners feel but, I'd personally suggest sticking with your use case. It's probably a good code practice though, to check whether a parent exists first before attempting to access nested properties. 

For example, the following would additionally prevent your TypeError from occurring. 

```js
if (req.body && req.body.email == null)
```
In any event, this approach (not defaulting to an empty object) was probably taken so that, for those using bodyParser, it's easy to determine whether a body was actually sent. 

If `req.body` defaulted to `{}`, you'd have no way to determine whether the client sent an empty object or didn't send anything at all. Leaving it undefined, enables us to perform checks like the following: 

```js
if (!req.body) res.send(400); // ensure a body is sent otherwise, error to client
```
Something like the above could provide additional context to the client should expected data be missing.

Anyway, hope this helps! 😃

**Comment by magnusdr** [comment]
Thanks for such quick and detailed response! 😃 

I now see why you choose to not define `req.body` if no body is sent. It makes more sense to me now!

You see, i'm coming from expressjs, and their bodyparser define `req.body` as an empty object if no body is defined. This caused some confusion for me yesterday 😕 

I have this impression of restify as more simple and minimalistic than expressjs, with less boilerplate and less need for configuration.

I guess i'll just continue using my custom middleware to fix my issue 👍
