### ISSUE TITLE
Restify changes error names

### ISSUE THREAD

**Issue by SamuelColacchia** [restify/node-restify#1446]
# Bug Report

## Restify Version
5.0.1

## Node.js Version
6.10.2

## Expected behaviour

Restify should emit a event with the name of a given error. 

> Before the error object is sent to the client, the server will fire an event using the name of the error.  (from documention)

## Actual behaviour

Restify emits the given error but changes the name by removing the word error. 

## Repro case

To reproduce pass a error to next other than a restify generated error.

Error given to next
```javascript
const err = new Error('TestError')
err.name = 'someError'
return next(err)
```

What one would expect to do based on reading the documentation.
Matching the event name with the name of the error. This unfortunately does not work.
```javascript
server.on('someError', (req, res, err, next) => {
  console.log('some error found!')
  return next()
})
```

Based on tracing through the code resitfy removes the word Error from the given name. So the event name you need is **_some_** instead of **_someError_**
```javascript
server.on('some', (req, res, err, next) => {
  console.log('some error found!')
  return next()
})
```

## Cause

Were the error name is changed
https://github.com/restify/node-restify/blob/dd66088f3067d4b0858a2dd0274c705faf374e0e/lib/server.js#L915

Were the error name is emmited 
https://github.com/restify/node-restify/blob/dd66088f3067d4b0858a2dd0274c705faf374e0e/lib/server.js#L941

## Are you willing and able to fix this?

No, unsure if this is a bug or intended.

If this is intended then the server documentation should be changed to inform users of this.

If this is a bug then the name emitted should be changed to reflect the name of the error based to next.

**Comment by DonutEspresso** [comment]
Thanks for the bug report! This is the expected behavior, so the docs instead should be updated.

**Comment by retrohacker** [comment]
Hey @SamuelColacchia,

Thank you for taking the time to create a repro case and explain what is going on here. For some context, from my understanding, this is the expected behaviour so that we play nicely with restify-errors where we map things like `BadRequestError` to a `BadRequest` event.

That being said, we appear to _break_ that convention here: https://github.com/restify/node-restify/blob/dd66088f3067d4b0858a2dd0274c705faf374e0e/lib/server.js#L904

@DonutEspresso: is `FormaterError` even valid in a post-async formatter world?

Anyways, this documentation change has landed :heart: closing this issue for now!

**Comment by retrohacker** [comment]
Also, this new GitHub thing where they expand code links in issues is pretty :fire:
