### ISSUE TITLE
What is alternative to handleUncaughtExceptions parameter?

### ISSUE THREAD

**Issue by jonatasfreitasv** [restify/node-restify#1653]
When active handleUncaughtExceptions:

```js
this.server = restify.createServer({
    handleUncaughtExceptions: true
});
```

Show this message:
`DEPRECATION WARNING: Due to deprecation of the domain module in node.js, all features in restify that depend on it have been deprecated as well. This includes `handleUncaughtExceptions` and `next.ifError()`. They will continue to work in 5.x, but consider them unsupported and likely to be removed from future versions of restify.`

What is the best way to have this feature but no use handleUncaughtExceptions parameter?

**Comment by DonutEspresso** [comment]
Hello - as the deprecation warning notes, domains have been deprecated in node core, so that means all restify features that depend on it are deprecated as well. However, as node itself has not yet provided a viable alternative, it's likely we'll keep the `handleUncaughtExceptions` feature in place for the foreseeable future.

**Comment by forstermatth** [comment]
I think this is an important issue to keep open unless there is another discussion happening elsewhere.

**Comment by SeanEire** [comment]
+1 to keep open. Deprecation warnings without an alternative or a plan to actually remove is confusing.
