### ISSUE TITLE
Plugin to make res.status() chainable.

### ISSUE THREAD

**Issue by june07** [restify/node-restify#1851]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request

## Use Case
Working on a multi service system where Express.js is used for some services and Restify for others.  The middleware is written such that it expects res.status to be chainable, so when passing in Restify objects, the middleware errors:

`TypeError: res.status(...).send is not a function`

I've written a plugin which provides this:
https://github.com/june07/node-restify/commit/0ec0d88347d6179bf9a5b8385ae0f3fad939ae4d

Following the proper flow to see if I can open a PR for this.

**Comment by ghermeto** [comment]
I don't oppose this change because we already return `this` on many of the `Response` methods, so it would be consistent. However,  this is definitely a breaking change and it would have to go out on 9.x.

For now, I believe the following would work for both Express and Restify:

```js
res.status(...);
res.send(...);
```

@restify/current-core any other thoughts?

**Comment by june07** [comment]
@ghermeto Thank you.  It's been almost 3 weeks without any further input from @restify/current-core so I've submitted a PR.  Also you are absolutely right with the suggestion below, if changing the code was feasible.  Otherwise when the code is upstream, or owned by someone else, this PR should help.

> ```js
> res.status(...);
> res.send(...);
> ```
