### ISSUE TITLE
Feature: add request timeout option to createServer

### ISSUE THREAD

**Issue by cmawhorter** [restify/node-restify#288]
If any handler/route neglects to call next/res.end(), the request will hang forever (or until client disconnects).

restify should automatically terminate and respond to requests that take too long to complete -- ideally as a createServer option.

Possible quickfix (untested):

``` javascript
  // end() reqs that aren't finished after 10s
  server.use(function(req, res, next) {
    next();

    setTimeout(function() {
      if ( ! res.finished )
      {
        console.log('response timed out');
        res.end();
      }
    }, 10000);
  });
```

Edit: By "requests" I meant the REST req from the client.  In other words, the HttpResponse should time out.

**Comment by okahara** [comment]
I apologize if I just haven't looked hard enough but does this functionality exist?

We are using restify@5.2.1 on Heroku and would like to end requests that have taken longer than Heroku's timeout of 30 seconds.

**Comment by hekike** [comment]
In my opinion not calling a `next` in one of the handlers is a programmatic error in userland code and is out of restify's scope.

However I believe that you use case is slightly different, but you can always cancel the middleware chain with `next(false)`.

**Comment by okahara** [comment]
Yes we agree that having a missed next/callback is an error that we'd rather not have. 

The situation is that we are having difficulties finding the problematic callback or lack of callback. Heroku queues request to a specific dyno and doesn't know that the problematic request is sitting there timed out and thus floods our logs with timedout requests so we are having a difficult time find exactly where our missed callback is. (https://help.heroku.com/AXOSFIXN/why-am-i-getting-h12-request-timeout-errors-in-nodejs)

Needless to say we were hoping we could log and kill the request that is problematic when it times out without our service crashing.

**Comment by retrohacker** [comment]
There are several issues wound up in this.

First: it is possible to "timeout" a request by doing something like:

```js
var timeout = setTimeout(() => res.end('', 408), 1000);
res.on('finish', () => clearTimeout(timeout));
```

Second:

Expiring a request like this does accomplish closing the connection, but it doesn't resolve the issues caused by not calling `next`. Invoking `next` is a strict requirement in restify, not doing so results in a slow memory leak since we hold onto references throughout the lifecycle of a request.

**Comment by okahara** [comment]
We agree that not calling next is probably our root problem unless we have a noisy neighbor on our Heroku Dyno hogging resources. We will probably be implementing a similar trick to monitor and log the request that times out as in @retrohacker 's first point.

Unfortunately, our service will still crash next time this issue arises but with the logging we'll either be able to track down the problematic route or have to more towards private dynos. I don't think adding this timeout feature would align with good practices of calling next 100% of the time either. We were just curious as to see if there was a way to log and monitor the request that times out and (a somewhat acceptable) way to kill it without our service dying.

**Comment by DonutEspresso** [comment]
This may not be foolproof for all scenarios, but if you inspect req.timers at the point of timeout that might give a hint as to which middleware it got stuck in.

**Comment by lfreneda** [comment]
@okahara same Heroku problem here. How did you handle it?

**Comment by okahara** [comment]
@lfreneda we didn't change anything within our code.

We believe our problem was caused noisy neighbor. We were not using dedicated dynos on Heroku which meant if a noisy neighbor spiked and hogged the CPU it actually affected us. We wrote more tests to confirm that we did not miss a callback/next and because the errors were so sporadic and would disappear once our service restarted we felt it was better to switch dyno types than add code we did not feel good about.

**Comment by lfreneda** [comment]
@okahara thanks a lot for sharing, I'll try to figure out things around here.

**Comment by fider** [comment]
It is possible to set native timeout:
```javascript
let restifyServer = restify.createServer();
restifyServer.server.setTimeout(xxx_ms); // default 2min
```
since `restifyServer.server` is created using one of below methods:
```javascript
http.createServer
https.createServer
http2.createSecureServer
spdy.createServer
```
`setTimeout` is native node http.Server method.

@okahara a lot of time has passed since your last comment, but track down your issue can be achieved by setting timeout to some low value and then ping each endpoint one by one at intervals (can be achieved in non-prod env only).
