### ISSUE TITLE
connectTimeout has no effect

### ISSUE THREAD

**Issue by thiagocaiubi** [restify/node-restify#405]
This example is not working properly. I am trying to set connectTimeout but it has no effect.

```javascript
var restify = require('restify');

var client = restify.createStringClient({
    url: 'https://www.google.com'
});

var start = new Date().getTime(),
    options = {
        url: "/",
        connectTimeout: 1,
        retry: false
    };

client.get(options, function(error, req, res, data) {
    console.log("Request took", new Date().getTime() - start, "ms");
    console.log(error);
    console.log(res.statusCode);
});
```
Looking inside http_client.js I realize that a cleatTime() call is right next the setTimeout function. So it is clearing timeout right after it has been set.

[https://github.com/mcavage/node-restify/blob/v1.4/lib/clients/http_client.js#L299](https://github.com/mcavage/node-restify/blob/v1.4/lib/clients/http_client.js#L299)

Any idea?

**Comment by micahr** [comment]
Not sure if this is still an issue, but connectTimeout should be in milliseconds, so it's possible that the timeout in your example was never run due to missing the 1ms window. If you are able to reproduce this with a timeout > 1ms, it could potentially be a bug, in which case, please re-open the issue.
