### ISSUE TITLE
Restify Homepage Documentation

### ISSUE THREAD

**Issue by ericelliott** [restify/node-restify#470]
It's hard for newcomers, and even people with some restify experience (like myself) to understand what value restify has over Express. After much googling around, I found this:

> restify is a node.js module purpose built to create REST web services in Node. restify makes lots of the hard problems of building such a service, like versioning, error handling and content-negotiation easier. It also provides built in DTrace probes that you get for free to quickly find out where your application’s performance problems lie. Lastly, it provides a robust client API that handles retry/backoff for you on failed connections, along with some other niceties.

Versioning, error handling, content-negotiation, DTrace, client API with retry/backoff... all of these sound like features in restify worth exploring that may indeed set it apart from Express.

This should probably replace the the text under "Why use restify and not express?" on the restify homepage. The current text just makes it sound like Express - features and docs + DTrace. Apparently, it's a lot more than that. I'm still not entirely sold, but at least the [Node Knockout description](http://blog.nodeknockout.com/post/34710903021/restify) has finally put me on the path towards enlightenment.

**Comment by micahr** [comment]
Thank you for the feedback. We are in the process of improving documentation as well as use cases where Restify makes sense over different web servers. As you point out, Restify is certainly a lot more than Express + Dtrace. 

I'm going to close this issue out as the basic documentation has evolved from when this issue was initially created. Please create a new issue if you have another specific documentation change you'd like addressed in the future.

Thanks!
