### ISSUE TITLE
conditionalRequest Plugin doesn't work

### ISSUE THREAD

**Issue by talha-asad** [restify/node-restify#473]
Hi,

I have been trying to get restify to send etag headers and check for if-\* headers to work nicely with my application. However when i try using the conditionalRequest plugin it does nothing.

Additionally the sample code on the homepage is also incorrect, since the first middleware never calls next, and thus the route is actually never served. Secondly the etag is hard coded, doesn't not look for etag from the route.

Can someone please provide me with a workable example, or perhaps help me understand how this is suppose to work.

**Comment by sebastiang** [comment]
Also observing.

**Comment by micahr** [comment]
Yikes, sounds like this is still a bug. Will add it to the next release.

**Comment by DeX3** [comment]
Bumping this, I'm facing exactly the same issue as @talha-asad, has this been resolved? Or am I missing something?

Imho the plugin should be tapping into the `after` event, otherwise it will always run before the actual routes and won't have a way to check for a dynamic ETag.

**Comment by DonutEspresso** [comment]
Agreed, the example is less than ideal, we should definitely make that better. On the other hand, can those of you affected take a look at this unit test, and see if the behavior is what you'd expect?

https://github.com/restify/plugins/blob/master/test/conditionalRequest.test.js#L46

These unit tests are probably a better example for how it should be used. Since the unit tests for these scenarios are passing, I'd imagine that at least the straightforward case should be working.
