### ISSUE TITLE
JSONP header being overwritten

### ISSUE THREAD

**Issue by mbell8903** [restify/node-restify#577]
So i was messing with JSONP and tried using app.use(restify.jsonp()); after my query parser.  This handler is called before my routing, and i found that if i call res.json in any of my route handlers, the json call overwrites the header, without ever checking to see if my jsonp handler already wrote it:

```
Response.prototype.json = function json(code, object, headers) {
    if (!/application\/json/.test(this.header('content-type')))
        this.header('Content-Type', 'application/json');

    return (this.send(code, object, headers));
};
```

Is this the intended functionality?  I would imagine that this check would be done at the end of routing, or at least in a JSONP call, even if res.json is called.  Maybe I'm wrong.

**Comment by micahr** [comment]
`res.json` is a helper method for the response, and is meant to make it simpler to send a plain json response. You shouldn't call it unless you are okay with it modifying the header. As such, this is expected behavior when calling this method.

Alternatively, you can set the content-type you'd like, then manually call `res.send`. This would allow you to do the appropriate checks before sending content to the client.
