### ISSUE TITLE
Large number of open connections observed in our use of JSONClient

### ISSUE THREAD

**Issue by ning-tan** [restify/node-restify#595]
Hi, we are currently creating a new JSONClient per outgoing request (and without explicitly calling close()). By doing so, we are observing some large number of open connections on the backing store (couchdb in this case).

What is the proper etiquette for using JSONClient? Should we call close()? Is there a performance problem by calling close() too aggressively? Is it better to create one JSONClient per server and keep using it?

Thank in advance for answering this.

**Comment by micahr** [comment]
It should be acceptable to create a JSONClient per request. You should most definitely call close after every request, to guarantee all sockets are closed, otherwise you will end up with the observed behavior of too many sockets open.

@jnordberg Setting agent to false will likely help because it isn't creating a tunnel for the traffic, but calling `close` should resolve your issue.

**Comment by retrohacker** [comment]
Marking this as resolved and/or stale due to inactivity. If calling `close` didn't solve the issue, comment below and we can revisit :heart:
