### ISSUE TITLE
"too few args to sprintf" when including `%` into an error message

### ISSUE THREAD

**Issue by merlinND** [restify/node-restify#646]
Minimum script to reproduce:

``` js
'use strict';

var restify = require('restify');

var server = restify.createServer();

server.get(/.*/, function(req, res, next) {
  res.send(new restify.NotFoundError('This % is not supposed to crash'));
  next();
});

server.listen(50000);
```

A request `GET http://localhost:50000/` will respond with:

```
{
code: "InternalError",
message: "too few args to sprintf"
}
```

I was also able to reproduce with other characters such as `$`, `^`, ...

**Comment by DonutEspresso** [comment]
In case it's not clear why this is the expected behavior, the standard errors in restify inherit from [VError](https://github.com/davepacheco/node-verror), so the constructors supports the same signatures as VError and WError. Thus,' %s' is used for [printf-style](https://github.com/davepacheco/node-extsprintf) messages. 

What's happening is that the VError constructor is asserting upon seeing a printf style signature, and upon seeing missing args will throw, which causes restify to send InternalError. You can handle this by listening to the uncaught exception error and handling as appropriate:

```js
server.on('uncaughtException', function() { ... });
```

Alternatively, decode your URLs if you intend on using them raw as the error string, or pass a second string as an empty param to your Error constructor:

```js
res.send(new restify.NotFoundError('This % is not supposed to crash', ''));
```
