### ISSUE TITLE
uncaughtException event not catching Exceptions outside of route scope

### ISSUE THREAD

**Issue by oleduc** [restify/node-restify#681]
Errors in packages or in files called using require are not catched by error handlers. Process events aren't called and restify neither. How does one go about logging all unhandled exception that might occur anywhere? 

Error event:
```javascript
  server.on('uncaughtException', function (req, res, route, error) {
      console.log(error);
  });
```

Route handler:
```javascript
  exports.someRoute = function(){
     // This doesn't trigger the event
     model.methodWithUnhandledException();
     // This triggers the event
     throw new Error('Route error');
  }
```

Model method:
```javascript
  exports.methodWithUnhandledException = function(){
     throw new Error('Model error');
  }
```

**Comment by micahr** [comment]
Restify does not handle Node errors. If you have an error requiring a file, you will need to handle it with `process.on('uncaughtException')` instead of `server.on('uncaughtException')`. It may seem confusing, but as you stated, errors that occur outside of the request lifecycle aren't handled as part of the Restify `domain`.
