### ISSUE TITLE
need clarification about Server.prototype._route

### ISSUE THREAD

**Issue by fghibellini** [restify/node-restify#695]
Hi,
I am trying to understand how the routing process works, but i got stuck on Server.prototype._route().

You can see that the router is queryied 2 times once with .get() and once with .find(). There's no documentation regarding the function of find. I was wondering why there are 2 calls to which the `cb`
argument is passed.

```
Server.prototype._route = function _route(req, res, name, cb) {
    var self = this;

    if (typeof (name) === 'function') {
        cb = name;
        name = null;
    } else {
        this.router.get(name, req, function (err, route, ctx) {
            if (err) {
                emitRouteError(self, req, res, err);
            } else {
                cb(route, ctx);
            }
        });
    }   

    this.router.find(req, res, function onRoute(err, route, ctx) {
        ...
            cb(route, ctx);
        }
    }); 
};
```

**Comment by micahr** [comment]
The code for the `_route` function has changed since this question was asked, it no longer can call `cb` twice.  I believe now (https://github.com/restify/node-restify/blob/bd0b524cd3635d4c230aec50702930ca5535bb04/lib/server.js#L740-L776) a route is only looked up once, and the presence or absence of `pre` functions for a route determine which method (`find` or `get`) are used.
