### ISSUE TITLE
Cannot get res._headers or anyway of getting header

### ISSUE THREAD

**Issue by mike-aungsan** [restify/node-restify#743]
server.on('after', function(req, res, route, error) {
   
  // I would like to get response header from here in order to do logging. 
  // is there anyway I can get res header from here?
});

OR

// I cannot see response header from here too. 

server.on('after', restify.auditLogger({

    //log : logger
    
    // name and serializers do not matter, steam matter
    log : bunyanLogger.createLogger({
        name    : 'audit',
        stream  : process.stdout,
    })

}));

Any help?

**Comment by yunong** [comment]
You can access the response headers via 

```javascript

res.getHeaders();

```

**Comment by yunong** [comment]
@mike-aungsan Is this still an issue?

**Comment by mike-aungsan** [comment]
Yes it is. I tried all the available function but all return nothing, empty array I guess.
All in the buyan logger, it does not log response header unless there is an error.

**Comment by yunong** [comment]
That means your response object does't have any headers at the point you're accessing them. Could you show the dump of the res object?

**Comment by elyscape** [comment]
@yunong `res._headers` only exists if `res.setHeader()` is called at some point.

`res._headers` defaults to null [and is properly initialized by `res.setHeader()`][initialize]. `res.setHeader()` is also [the only thing that sets it][set]. `res.writeHead()` will call `res.setHeader()` if passed headers [and `res._headers` already exists][writehead] (i.e. `res.setHeader()` has been called before), but otherwise does not bother for performance reasons. As such, if response headers are left at default or only provided via `res.writeHead()`, the field defaults to `null`. Bunyan's default serializer [provides `res._header`][bunyan], which is the string HTTP header. Example:
```http
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 07 Apr 2017 23:21:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

Additionally, [`res.getHeaders()` internally relies on `res._headers`][getheaders], so that can't be used to reliably retrieve the response headers.

<details>
<summary>A script you can use to verify this</summary>

```javascript
'use strict';
const http = require('http');

http.createServer( (req, res) => {
  console.log();
  console.log('start - res._headers:');
  console.log(res._headers);
  console.log('start - res._header:');
  console.log(res._header);
  res.writeHead(200, {'Content-Type': 'text/plain'});
  console.log('writeHead - res._headers:');
  console.log(res._headers);
  console.log('writeHead - res._header:');
  console.log(res._header);
  res.end('OK\n');
  console.log('end - res._headers:');
  console.log(res._headers);
  console.log('end - res._header:');
  console.log(res._header);
  console.log();
}).listen(8080);

http.createServer( (req, res) => {
  console.log();
  console.log('start - res._headers:');
  console.log(res._headers);
  console.log('start - res._header:');
  console.log(res._header);
  res.setHeader('Content-Type', 'text/plain');
  console.log('setHeader - res._headers:');
  console.log(res._headers);
  console.log('setHeader - res._header:');
  console.log(res._header);
  res.writeHead(200);
  console.log('writeHead - res._headers:');
  console.log(res._headers);
  console.log('writeHead - res._header:');
  console.log(res._header);
  res.end('OK\n');
  console.log('end - res._headers:');
  console.log(res._headers);
  console.log('end - res._header:');
  console.log(res._header);
  console.log();
}).listen(8081);
```
</details>
<details>
<summary>Sample output from a request on port 8080 (i.e. no call to `res.setHeader()`)</summary>

```
start - res._headers:
null
start - res._header:
null
writeHead - res._headers:
null
writeHead - res._header:
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 07 Apr 2017 23:21:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked


end - res._headers:
null
end - res._header:
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 07 Apr 2017 23:21:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```
</details>
<details>
<summary>Sample output from a request on port 8081 (i.e. `res.setHeader()` is called)</summary>

```
start - res._headers:
null
start - res._header:
null
setHeader - res._headers:
{ 'content-type': 'text/plain' }
setHeader - res._header:
null
writeHead - res._headers:
{ 'content-type': 'text/plain' }
writeHead - res._header:
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 07 Apr 2017 23:27:01 GMT
Connection: keep-alive
Transfer-Encoding: chunked


end - res._headers:
{ 'content-type': 'text/plain' }
end - res._header:
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 07 Apr 2017 23:27:01 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```
</details>

[initialize]: https://github.com/nodejs/node/blob/v7.8.0/lib/_http_outgoing.js#L376-L377
[set]: https://github.com/nodejs/node/blob/v7.8.0/lib/_http_outgoing.js#L380
[writehead]: https://github.com/nodejs/node/blob/v7.8.0/lib/_http_server.js#L177
[bunyan]: https://github.com/trentm/node-bunyan/blob/1.8.10/lib/bunyan.js#L1113
[getheaders]: https://github.com/nodejs/node/blob/v7.8.0/lib/_http_outgoing.js#L406-L418
