### ISSUE TITLE
Question: open to using `bind` rather than `self = this`?

### ISSUE THREAD

**Issue by jameswomack** [restify/node-restify#854]
Using `self` strikes me as hacky given the language has syntax built-in for handling context transfer. Would the Restify team be open to using `bind` instead?

I believe the worst-case scenario would look like this:
```js
Server.prototype._handle = function _handle(req, res) {
    var routeAndRun = (function routeAndRun() {
        this._route(req, res, function (route, context) {
            req.context = req.params = context;
            req.route = route.spec;

            var r = route ? route.name : null;
            var chain = this.routes[r];

            this._run(req, res, route, chain, function done(e) {
                this.emit('after', req, res, route, e);
            });
        }.bind(this));
    }).bind(this);

    if (this.before.length > 0) {
        this._run(req, res, null, this.before, function (err) {
            if (!err) {
                routeAndRun();
            }
        });
    } else {
        routeAndRun();
    }
};

```

**Comment by DonutEspresso** [comment]
The trade off is perf related, on a multi-tenant environment where you're taking hundreds/thousands of rps, every little bit counts. The lower level the code, the closer to the metal it should be, in order to keep from becoming any sort of bottleneck. From that perspective, using `self` is always the most performant option. It's been awhile since I did any sort of testing, but if I recall: 

self (closure) > call > apply > bind

That said, I love `bind`, and at the application level I would have very little reservations using it.

**Comment by jameswomack** [comment]
I thought that would be the reason, and I'm glad because it makes sense ;)
A couple of thoughts in response:
1. As a dev that's sat with a lot of ObjC code, I would probably say that `server` or even `serverContextRef` would be clearer and prevent using something that looks like a keyword but  isn't. `self` may be a convention but it's always struck me as more of a hack.
2. Does Restify have specific performance goals & if so, how are they tested?

**Comment by DonutEspresso** [comment]
1) I'm not sure I follow that one is worse than the other, since at this point it's really just picking a variable name that makes it clear it's a substitute for `this` within the closure. I'd argue that we want a name that most accurately describes `this`, and not some other server object, or an instance of the server class, or could be confused for another variable. IMHO, `self` makes that distinction clearer than any other variable, and is a well understood convention (along with `that`). 

2) This is a great question, and one that I don't have an immediate answer to. I'd like to get some synth benchmarks set up, but some questions remain around how we make that easily testable/repeatable/consistent. Certainly, having some baseline is better than nothing. Created #860 to track.

**Comment by jameswomack** [comment]
Re: 1, I'm onboard with your reasoning. 

Re: 2 I'd be up for creating some benchmarks with wrk or bench-test.
