### ISSUE TITLE
ifError return the error to the client and not emit uncaughtException

### ISSUE THREAD

**Issue by omerlh** [restify/node-restify#865]
Hey
I tried to use the api of "ifError". As I understand from reading this [issue](https://github.com/restify/node-restify/issues/569), it seams like ifError suppose to throw exception and those should emit the 'uncaughtException' event. But, to my surprise, I tried it in my code and it simply return the error to the client. Is it on purpose? Now, I know I can register to event per error, but I prefer to register to any exception returned from any controller.
The code that demonstrate the problem:
```javascript
var restify = require('restify');

var server = restify.createServer({
  name: 'myapp',
  version: '1.0.0'
});

server.get('/', function (req, res, next) {
  return next.ifError(new Error('error'));
});

server.on('uncaughtException', function (req, res, route, error) {
	console.log('error');
});

server.listen(7070, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```
I am using restify version 3.0.3 (latest). I think this is happen because of this implementation of ifError:
```javascript
function ifError(n) {
    function _ifError(err) {
        if (err) {
            err._restify_next = n;
            throw err;
        }
    }

    return (_ifError);
}
```
Which add the next in chain (which is restify sending logic) to the error. Than, on the domain exception handling:
```javascript
if (err._restify_next) {
            err._restify_next(err);
        } else {
            log.trace({err: err}, 'uncaughtException');
            self.emit('uncaughtException', req, res, route, err);
        }
```
So, because any exception have the next parameter, they are not passed to the uncaughtException event.
Thank you,
Omer

**Comment by DonutEspresso** [comment]
The behavior of `ifError` is really the same thing as doing:

```js
res.send(err);
```

Per the docs, you could do something like:

```js
function(req, res, next) {
    next.ifError(err);
    res.send('hello world');
    next();
}
```

And restify will send the error as the response if it is indeed an error object, otherwise it will skip over `ifError` and send the correct response.

If you really want to use the uncaughtException handlers, you can just throw right in your handler:

```js
function(req, res, next) {
    throw new Error('bad!');
}

server.on('uncaughtException', function(req, res, route, err) {
    // you'll get the bad error you threw above
});
```

**Comment by omerlh** [comment]
But this is opposed to what said explicit in this [issue](https://github.com/restify/node-restify/issues/569):
>The ifError function throws the error, while passing the error to next does not throw, unless it reaches the end of the chain and isn't handled.
I am misunderstanding?

**Comment by DonutEspresso** [comment]
The explanation given in that issue is technically correct, but the behavior from consumer standpoint is a little bit inconsistent. When restify throws that error, the domain will [catch](https://github.com/restify/node-restify/blob/master/lib/server.js#L951) the thrown error, then call next() with the error (resulting in your error being sent as the response).

It's sugar for directly calling `res.send(myErr)`, although the documentation is not very clear about how/why that works. Given the confusion the API has caused, I think there's good reason to consider removing/modifying the API in the next major release. Any feedback would be appreciated.

**Comment by omerlh** [comment]
I see, this is really confusing. IMHO, I think this synthetic sugar (throw if error) is very nice and can help to remove a log of builer plot code like this:
```javascript
if(err){
    throw err;
}
```
What do you think?

**Comment by DonutEspresso** [comment]
Throwing arbitrarily in an async environment only works the way it does today because of domains, and with them being deprecated this is probably not a desirable problem.

As an alternative, you can call `next(err);`  with a specific type of Error, and then attach listeners for that class of errors, instead of using uncaughtException as a catch all:

```js
function (req, res, next) {
    var myErr = new UnauthorizedError('no credentials');
    next(myErr);
}

// elsewhere...
server.on('UnauthorizedError', function(req, res, err, next) {
    // do something
});
```

More info available in the (error-handling section)[http://restify.com/#error-handling] of the docs.

**Comment by omerlh** [comment]
OK, thanks. I will give it a try.
