### ISSUE TITLE
Error param when fn emitRouteError emits 'after' event

### ISSUE THREAD

**Issue by nicolaspeixoto** [restify/node-restify#888]
I'm trying to log all my server requests just using 'after' event emitted from server. But when i send an error in next function the error isn't sent to after event.

```javascript
server.get('/hello/:name', function(req, res, next) {
  // some internal unrecoverable error
  var err = new restify.errors.InternalServerError('oh noes!');
  return next(err);
});
```
emitRouteError:
``` javascript
   req.log.trace({name: name, err: err}, 'entering emitRouteError');
    if (server.listeners(name).length > 0) {
        server.emit(name, req, res, err, once(function () {
            server.emit('after', req, res, null);
        }));
    } else {
        res.send(err);
        server.emit('after', req, res, null);
    }
```
How can i log the error if i don't want to use a listener for each type of error?

**Comment by micahr** [comment]
You can catch all error events with `uncaughtException`: 

```javascript
server.on('uncaughtException', function(req, res, route, err) {
    // log and cleanup your error here
});
```

This is good practice to ensure you are logging all possible events. If, inside this function, you want to handle individual errors in different ways, you should be able to.

As for logging everything in the `after` event, I would recommend using the audit logger with Bunyan to ensure you get all the information about your request: http://restify.com/#audit-logging.

**Comment by nicolaspeixoto** [comment]
I am already using uncaughtException, but in this case, i'm sending the error on next function, and i need to build my own log function.

for example: 
``` javascript
if(err){
    next(new InternalServerError(err, 'oh noes!'));
}

server.on('after', function(req, res, route, err){
    /* err is null! */
    if(err){
         req.log.error(err);
     }
}
```
Why emitRouteError() doesn't send the error param?

**Comment by micahr** [comment]
`emitRouteError` is called when a route couldn't be found using `router.get` or `router.find`. In that case, the request is effectively over because a suitable routing chain couldn't be determined. Is is assumed that if you got the error from the router, then you weren't able to find a route.

[The code](https://github.com/restify/node-restify/blob/master/lib/server.js#L828-L842) for handling an error passed to `next` will only send the error to the callback, which will in turn [send](https://github.com/restify/node-restify/blob/master/lib/server.js#L713) it to `after`, if there is a listener for that error. The normal behavior for sending an error to `next`, is that you are wanting to send this to the client. If there is no listener for any given error, then it is assumed that the application developer won't be handling the error and it needs to be sent to the client.

The best course of action if you are wanting to log individual errors, is to set up handlers for them.

**Comment by DonutEspresso** [comment]
@nicolaspeixoto, as @micahr mentioned RouteErrors are only for errors in the routing of a request (i.e., can we find a handler for the requested resource, and does the version match, etc.)

There is currently no "catch all" event for all Errors returned via `next()`, you'd have to add listeners to each one you care about. Error listeners are fired before the response is sent, giving you an opportunity to actually __modify__ the content being sent back (instead of sending back a serialized error object). 

If you don't want to modify the content, and only care about logging errors specifically, which is what you want, you can use the `after` event, which gives you the following signature:

```js
server.on('after', function(req, res, route, err) { ... });
```

You can attach multiple functions to the after event, each one firing in the order they were attached. So if you're already using auditLogger, just add another one:

```js
server.on('after', restify.auditLogger({...});
server.on('after', function(req, res, route, err) {
    if (err) {  
        // do some special logging
    }
});
```

**Comment by DonutEspresso** [comment]
I whipped up a short demo and it is working:

```js
var restify = require('restify');
var bunyan = require('bunyan');

var log = bunyan.createLogger({
    name: 'test'
});

var server = restify.createServer({
    log: log
});

server.on('after', function(req, res, route, err) {
    console.log('my custom after!')
    if (err) {
       console.log('my custom after err found');
    }
});

server.get('/', function(req, res, next) {
    return next(new Error('foobar'));
});

server.listen(3000);
```

If this does not work for you, let me know. Can you try and put together a gist for your exact problem? It's possible the error is coming from someplace else.

**Comment by micahr** [comment]
Thanks @DonutEspresso that is very helpful. @nicolaspeixoto can you let us know how your code differs from the example so we can figure out where things are breaking down?

**Comment by nicolaspeixoto** [comment]
@mbjordan You're right, the problem is not about emitRouteError. It was my mistake. 
The problem is the same of #667, but i didn't see this issue before opening this.

The #892 will resolve my problem.

Thank you guys. @DonutEspresso @micahr

**Comment by DonutEspresso** [comment]
Closing - this will go out with 5.x release.

**Comment by nicolaspeixoto** [comment]
Thanks @DonutEspresso
