### ISSUE TITLE
Improve Release Process

### ISSUE THREAD

**Issue by yunong** [restify/node-restify#913]
# WHY

We need a concrete process for managing restify releases. In the past, the process has been ad-hoc, manual, and prone to errors.

**Comment by yunong** [comment]
We would like to be able to update CHANGES.md everytime a pull request is merged. Should be able to integrate with github hooks to kick off CI to do this.

**Comment by yunong** [comment]
In the mean time, manually update CHANGES.md after merging a PR.

**Comment by yunong** [comment]
Release process.

1) Add a tag via `npm version patch...`
2) update CHANGES.md

**Comment by micahr** [comment]
After our ( @yunong, @DonutEspresso, and @jameswomack ) discussion yesterday, I wanted to capture a few things here.

### Release / Development Process

1. Changes will be done in the branch of the major version they are targeting.
    * For example, work targeting milestone v5.x should be done in that branch, while bug fixes and other minor changes can be done in other release branches, such as v4.x if they need to be released before the next major / minor release.
    * Master should be kept up to date with the current released and stable version of code. Which means after a new stable version is released, it is merged to Master.
2. When a release is ready to be made:
    * The README.md and CHANGES.md should be updated on that branch.
    * Version numbers in package.json should be updated
    * A tag with the version number should be created

**Comment by retrohacker** [comment]
These sound great, a `CONTRIBUTING.md` would be a great place for this stuff.

**Comment by retrohacker** [comment]
Proposed release process:

## Releases are determined by PRs not sprints

As opposed to committing to work and features up front for a release (i.e. the currently blocked 5.x release), I propose that we cut releases based on features that have landed via a PR. This will increase the release cadence of the project and will ensure user's contributions make it to npm as quickly as possible. To support that I suggest we change the way we treat branches.

## Semver branches

I propose we create the following branches: `patch`, `minor`, `major`. When a PR is opened against the project, we will determine what degree of changes it introduces and merge it into the appropriate branch. When enough work has built up into that branch, we can rebase against the current `master` branch, increment the version in `package.json`, tag, and merge into master.

This means the `master` branch always reflects what is out on npm.

## CI/CD releases

Since `master` reflects the latest release on npm, when a PR is merged into that branch, CI/CD can safely handle pushing the release to npm.

**Comment by retrohacker** [comment]
This has the advantage of shipping early and often, and avoids the situation where contributors commit to work upfront but don't have the bandwidth to tackle it. As opposed to having milestones for releases, we can have milestone for features. This should help everyone feel better :smile:

**Comment by DonutEspresso** [comment]
How do we manage lifecycle of the patch, minor, and major branches? These sound like long lived branches - how do we easily determine where they are (commit history wise) in relation to each other or to master?

One of the things we've been experimenting in another repo that's been pretty successful is using the commit messages to automatically determine the next release version - i.e., looking at the commit history since last tag, and using conventional change log commits we can programatically determine the next semver. This could be another way to make releases "any time" easier, though it requires more descriptive commit messages along with a valid prefix.

**Comment by retrohacker** [comment]
Huge :+1: to using conventional changelog ^_^

I agree with that whole flow, with on caveat: a merge to master should always trigger a release to npm. That release process could essentially be TravisCI (or similar) automating the conventional change log cut.

In regards to `major`, `minor`, and `patch`, my suggested workflow might be a little excessive. Having a `major` (or `next`) branch may be enough. Essentially what I would like to have is a branch that is consistently getting rebased against `master`, where we can batch multiple breaking changes into a single semver major release (a lighter version of what the 5.x branch is right now). The rebasing process will help a lot in getting bug fixes out the door. Just because we are working on a large feature, bug fixes shouldn't be blocked. By shipping the bug fix to `master` and rebasing `next`, we can ship these fixes immediately but still get them into the next major release.

**Comment by retrohacker** [comment]
Alternatively, we could all together drop batching multiple breaking changes, and release each breaking change as it's own semver major using conventional change logs and merging directly to master.

**Comment by retrohacker** [comment]
https://github.com/restify/node-restify/blob/master/CONTRIBUTING.md now exists, improvements and automation can be submitted as PRs.
