### ISSUE TITLE
504 when no formatter exists for 'accept' header

### ISSUE THREAD

**Issue by JoshRagem** [restify/node-restify#937]
if a client makes a request with `accept` header set to a format for which the server has not formatter (example: `text/html` is not built in and the dev has not defined a formatter for it), the client will never receive any response and will eventually time out.

**Comment by DonutEspresso** [comment]
restify should always return a response using application/octet-stream, even if the client requests a content-type you don't have a formatter for.

That said, I did dig into this, there is a bug where if the response is _not_ setting a content-type header AND you don't have a formatter for it, then it will hang. Can you make sure you're setting a content-type header on the response?

**Comment by JoshRagem** [comment]
I create the server like so:
```
var app = restify.createServer({
  log: log,
  formatters: formatters,
  accept: ["application/json"],
  contentType: ["application/json"]
});
```

And I thought that would set the content type of responses. Is this not so? (I just changed from 2.8 so maybe that option is of null effect)

**Comment by DonutEspresso** [comment]
I am not sure in 2.x, but `createServer` no longer takes accept or contentType anymore. What you'll want to do is set the content type for a response in a handler somewhere:

```js
function handler(req, res, next) {
  res.header('content-type', 'text/html');
  res.send('<html>foobar</html>');
  next();
}
```

restify will infer a formatter based on the content-type header you've set, falling back on application/octet-stream if no match is found. Since your server can presumably serve multiple types of payloads (html/json/whatever) you need to be explicit about it.

**Comment by JoshRagem** [comment]
makes sense. thanks.
