### ISSUE TITLE
Transforming the Resonse after sending

### ISSUE THREAD

**Issue by rmoskal** [restify/node-restify#949]
I'd love to be able to decorate my JSON responses in a transparent matter as part of a pipeline. Ideally I'd like to do something like this:

    app.get('/safe/closet/:userId', 
    function (req, res, next) {
        res.send({key:"val}
        next()}, 
    function(req, res, next){ 
         res._body.key = {deeper:'foo}
         res.send( res._body)}
    ); 

But you can't seem to be able to do this.  The issue is here: 
    https://github.com/restify/node-restify/blob/5.x/lib/response.js#L340

    if (body !== undefined) {
        this.format(body, _cb);
    } else {
        _cb(null, null);
    }

The code takes the first branch in the loop and this format never returns. Is this behavior by design?

**Comment by DonutEspresso** [comment]
There's a bunch of syntax errors in your example, and you can't call `res.send()` twice, but if it's hanging on your formatter it's probably because you have a custom formatter defined that's not invoking the callback. Check the [documentation](http://restify.com/#content-negotiation) on formatters. If you're upgrading from an older version, all formatters are now async and must invoke the callback.

**Comment by rmoskal** [comment]
I guess that's the root of my problem. I want to call send multiple times.  I want to build up my response gradually in steps, decorating and enriching the JSON. I know I could do this by using a property on the request  or on the response (a pattern I've used before). But I was hoping to do it in a less ceremonious, obstrusive fashion.

**Comment by DonutEspresso** [comment]
Yeah, that's just how the API is designed. You should think of `res.send` as sugar for calling `res.write`, then right afterward calling `res.end` to flush the response. You can call `res.write` as many times as you want, but since that's using the underlying stream implementation each time you call it that chunk of data will be written immediately. 

If you want to do mutation of a payload over multiple handlers prior to flushing the response, you should just manage your own objects/namespaces on req/res. You could create a module to help you set/get from known/whitelisted namespaces if that's desirable, but that's something you'd want to handle yourself at the application layer, and not within restify. Hope that helps somewhat. 

Did you figure out if the formatter was causing your response to hang?

**Comment by rmoskal** [comment]
I didn't have a formatter.  It was the double call. I understand what you are saying, I'm tempted to monkey patch the code to give me a "buffered" version for transformations
