### ISSUE TITLE
Exception/Error doesn't trigger uncaughtException if there is a Promise in chain

### ISSUE THREAD

**Issue by jishi** [restify/node-restify#962]
Considering this code:

```
var restify = require('restify');

function throwAnError(req, res, next) {
  throw new Error('This should trigger uncaughtException');
}

function promisedNext(req, res, next) {
  (Promise.resolve())
  .then(function () {
    next();
  });

  //setImmediate(() => {
  //  next();
  //});
}

var server = restify.createServer();
server.get('/error', promisedNext, throwAnError);

server.listen(8080, function() {
  console.log('%s listening at %s', server.name, server.url);
});

server.on('uncaughtException', (request, response, route, error) => {
  console.error(error, error.stack);
  response.send(500);
});
```

This code doesn't trigger the uncaughtException event, because of the promise in the route handler. I first thought it had something to do with the asynchronous execution, but a setTimeout or setImmediate do work, and as expected.

The next() call is invoked, since a functioning final handler will finish the request as expected, it's just seem to be error bubbling that somehow get's blocked.

Is this somehow related to #875? 

This was tested with Restify 4.0.3

**Comment by doodlemeat** [comment]
I don't think promises are supported as handlers.

**Comment by DonutEspresso** [comment]
The Promise specification is designed such that all functions invocations are wrapped in try/catch - that's what allows you to put a `catch()` at the end of your Promise chains that can handle any thrown errors. That also means that when you `throw`, that error is getting caught by the Promise and not by restify. Unfortunately, the Promise spec doesn't let you "escape" from the domain of the Promise. It's Promises all the way down.

@jishi your example with setTimeout and setImmediate work exactly because they are async and you can't try/catch them. If you want to use Promises, you can use a library that supports `done()`. I believe Bluebird supports this. `done()` works like `then()`, but lets you escape from the Promise domain, which means your throws will then actually work as intended.

**Comment by DonutEspresso** [comment]
For reference: http://bluebirdjs.com/docs/api/done.html
