### ISSUE TITLE
What DTRACE have to do with RESTIFYing ???

### ISSUE THREAD

**Issue by greggman** [restify/node-restify#992]
Sorry if this is a stupid question but, what does DTRACE have to do with making a REST API?

The fact that node-restify is depending on DTRACE makes this package incompatible with all kinds of situations. I was using an old version of the package, upgrade, now I have to find a new solution because of that dependency.

At a glance, not knowing the reasons for adding it it certainly seems like an unreasonable dependency so I thought I'd ask

**Comment by micahr** [comment]
Dtrace is an [optional dependency](https://github.com/restify/node-restify/blob/5.x/package.json#L81). If your platform doesn't support Dtrace it won't be installed (or can be safely ignored).

Restify's use of Dtrace is for inspection and instrumentation which provides a lot of observability into the internals of the application without a lot of overhead. You are free to use or not use this functionality without any impact on your application.

Out of curiosity, what kind of situation is incompatible with using Dtrace (presumably Windows)?

**Comment by greggman** [comment]
Any usecase that tries to package up the dependencies and not require the end user to have a full dev system with C++ compiler

**Comment by micahr** [comment]
That is an interesting idea. I don't believe we had considered having the instrumentation as a separate package. Because it is optional, it should be simple enough for those that don't want it or aren't able to install it to ignore and not use that functionality.

I can understand not wanting a native module installed when you are packaging up your application for deployment to a different platform / architecture. Thanks for the feedback!
