### ISSUE TITLE
Custom handler => 404 will not send response

### ISSUE THREAD

**Issue by C4Phone** [restify/node-restify#999]
Running the following code with the latest restify (installed using NPM), if an user tries to load any page other than "/hello" or "/400", the web browser will be always waiting for response.

 
```javascript
var restify = require('restify');
var server = restify.createServer();

server.get('/hello/', (req, res, next) => {
  res.send("hello");
});

server.get('/400/', (req, res, next) => {
  return next(new restify.errors.BadRequestError());
});

server.on('NotFound', (req, res, err, cb) => {
  console.log("in error handling of 404");
  console.log("did not send response during this handler");
  console.log("cb = " + cb);
  return cb();
});

server.on('BadRequest', (req, res, err, cb) => {
  console.log("in error handling of 400");
  console.log("did not send response during this handler");
  console.log("cb = " + cb);
  return cb();
});

server.listen(8181, function() {
  console.log('%s listening at %s', server.name, server.url);
});
```

It seems that although generally speaking, adding a handler for 4xx errors will not prevent restify from sending responses (for example accessing "/400" still works fine), the handling for 404 will be broken by adding our own level of error handling.

This lack of symmetry might not be a huge problem but now we have to write our own code to generate error messages for all HTTP failures, because otherwise they might not share the same format.

**Comment by lafickens** [comment]
The cause could be `server#emitRouteEvent`:

```javascript

// ...
if (server.listeners(name).length > 0) {
  server.emit(name, req, res, err, once(function () {
    server.emit('after', req, res, null);
  }));
} else {
  res.send(err);
  server.emit('after', req, res, null);
}
```

There isn't necessarily an "after" event registered in `EventEmitter`. If any event handler is registered, the condition is true and then a potentially nonexistent event is fired, and `res.send` is not called. Is this done deliberately?

**Comment by DonutEspresso** [comment]
Good find, folks. It does look rather deliberate, though as noted it means we now have to ways of dealing with errors:

```js
server.on('BadRequest', function(req, res, err, cb) {
  err.body = 'boom! bad request!';   // the body of the error becomes the response
  return cb();
});

server.on('NotFound', function(req, res, err, cb) {
  res.send('boom! not found!');    // in NotFound, must manually send the response
  return cb();
});
```

I was never really a fan of the err.body pattern, I think it would be good to come to agreement on something for 5.x. I suspect we'd like to support both use cases of 1) users being able to use res directly to send out a response (which isn't possible today because of the err.body pattern), and 2) users just wanting to use the listener to do something like log metrics but have restify send out the default response. 

Ideally I'd like to be able to inspect whether the response was already flushed, but not sure if that's possible if the callback was invoked before the response has finished flushing. Perhaps the callback can hint to restify whether or not a response was manually written out?

**Comment by DonutEspresso** [comment]
We've updated NotFound handler to act like all the other error handlers.
